### ISSUE TITLE
Reading/recreating calibrated models fails in v3.7.1, v3.7.2 and v3.8.1

### ISSUE THREAD

**Issue by yanhong-zhao-ef** [facebookexperimental/Robyn#524]
## Describe issue
Once calibration step is added to the modeling process, I can't recreate any of the models from that run. The error message it this from the reproducible example I have included for the latest version. It is taken from demo.R and simply uncommented the calibration code.
```
RobynRecreated <- robyn_recreate(
+   json_file = json_file,
+   dt_input = dt_simulated_weekly,
+   dt_holidays = dt_prophet_holidays,
+   quiet = FALSE)
>>> Recreating model 4_161_1
Imported JSON file succesfully: /Users/yanhongzhao/EF/next-gen-mmm/Robyn_202211031129_init/RobynModel-4_161_1.json
>> Running feature engineering...
Input data has 208 weeks in total: 2015-11-23 to 2019-11-11
Initial model is built on rolling window of 92 week: 2016-11-21 to 2018-08-20
Error in `filter()`:
! Problem while computing `..1 = .data$solID %in% allSolutions`.
Caused by error in `.data$solID`:
! Column `solID` not found in `.data`.
Run `rlang::last_error()` to see where the error occurred.
Warning messages:
1: In is.na(date_var_dates) || is.infinite(date_var_dates) :
  'length(x) = 2 > 1' in coercion to 'logical(1)'
2: In is.na(date_var_dates) || is.infinite(date_var_dates) :
  'length(x) = 2 > 1' in coercion to 'logical(1)'
3: In check_calibconstr(calibration_constraint, OutputModels$iterations,  :
  Input 'calibration_constraint' set for top 10% calibrated models. 0 models left for pareto-optimal selection. Minimum suggested: 500
> rlang::last_error()
<error/rlang_error>
Error in `filter()`:
! Problem while computing `..1 = .data$solID %in% allSolutions`.
Caused by error in `.data$solID`:
! Column `solID` not found in `.data`.
---
Backtrace:
  1. Robyn::robyn_recreate(...)
 14. rlang:::abort_data_pronoun(x, call = y)
```
I have run into the similar issue with my own dataset where it will complain "Error while running robyn_mmm(); providing PARTIAL results" triggered in the model.R script and the downstream function will get an error but I haven't seen that with the demo.R script 

## Provide reproducible example
[robyn_debug.txt](https://github.com/facebookexperimental/Robyn/files/9925510/robyn_debug.txt)

## Environment & Robyn version
Make sure you're using the latest Robyn version before you post an issue.
- Check and share Robyn version: `packageVersion("Robyn")`
- R version (Please, check and share: `sessionInfo()` or `R.version$version.string`)
Robyn version: 3.8.1
R version 4.2.2 (2022-10-31)
Platform: aarch64-apple-darwin21.6.0 (64-bit)
Running under: macOS Monterey 12.3

**Comment by yanhong-zhao-ef** [comment]
Just tried running on my own data with the updated v3.8.1 code with calibration and here is the error reported: the warning "Error while running robyn_mmm(); providing PARTIAL results" doesn't really help when debugging for error.

```R
>>> Starting 10 trials with 2000 iterations each with calibration using TwoPointsDE nevergrad algorithm...
  Running trial 1 of 10
  |                                                                      |   0%Timing stopped at: 0.846 0.533 0.225
Error while running robyn_mmm(); providing PARTIAL results
Error in {: task 1 failed - "non-numeric argument to binary operator"

 
  Finished in 0.01 mins
Error in `arrange()`:
! Problem with the implicit `transmute()` step.
✖ Problem while computing `..1 = .data$nrmse`.
Caused by error in `.data$nrmse`:
! Column `nrmse` not found in `.data`.
Backtrace:
     ▆
  1. ├─global run_robyn_mmm(config)
  2. │ └─Robyn::robyn_run(...)
  3. │   └─Robyn::robyn_train(...)
  4. │     └─Robyn::robyn_mmm(...)
  5. │       └─... %>% as_tibble()
  6. ├─tibble::as_tibble(.)
  7. ├─dplyr::arrange(., .data$nrmse)
  8. ├─dplyr:::arrange.data.frame(., .data$nrmse)
  9. │ └─dplyr:::arrange_rows(.data, dots)
 10. │   ├─base::withCallingHandlers(...)
 11. │   ├─dplyr::transmute(new_data_frame(.data), !!!quosures)
 12. │   └─dplyr:::transmute.data.frame(new_data_frame(.data), !!!quosures)
 13. │     └─dplyr:::mutate_cols(.data, dots, caller_env = caller_env())
 14. │       ├─base::withCallingHandlers(...)
 15. │       └─mask$eval_all_mutate(quo)
 16. ├─nrmse
 17. ├─rlang:::`$.rlang_data_pronoun`(.data, nrmse)
 18. │ └─rlang:::data_pronoun_get(...)
 19. └─rlang:::abort_data_pronoun(x, call = y)
 20.   └─rlang::abort(msg, "rlang_error_data_pronoun_not_found", call = call)
Warning messages:
1: In is.na(date_var_dates) || is.infinite(date_var_dates) :
  'length(x) = 2 > 1' in coercion to 'logical(1)'
2: In is.na(date_var_dates) || is.infinite(date_var_dates) :
  'length(x) = 2 > 1' in coercion to 'logical(1)'
3: In value[[3L]](cond) :
  Error while running robyn_mmm(); providing PARTIAL results
Execution halted
```

Running the same data without calibration works without a hitch

**Comment by gufengzhou** [comment]
Hey, very sorry about this bug that is also reported by another user #520. I just pushed another fix. Could you please update and test? thanks!

**Comment by yanhong-zhao-ef** [comment]
> Hey, very sorry about this bug that is also reported by another user #520. I just pushed another fix. Could you please update and test? thanks!

Is this fix on the main branch? Is it the one from an hour ago?

**Comment by yanhong-zhao-ef** [comment]
Updated the code and tried it out. The problem still exist. 

I read through the other issue and my 2nd comment above is the same as the latest on that issue.

The first comment (original comment I opened the issue with) is likely different and you can use the script I provided to reproduce the bug.

**Comment by gufengzhou** [comment]
yes, and that's to fix the bug. because of the new calibration function, we require one more column, calibration_scope, in the calibration_input table. please check [here](https://github.com/facebookexperimental/Robyn/blob/main/demo/demo.R#L263). If you're using experiments to calibrate, just put "immediate" in it.

**Comment by yanhong-zhao-ef** [comment]
Can confirm that in both the script I provided and my own script that column exists and the bugs are there

**Comment by gufengzhou** [comment]
ok, to clarify: after updating and restarting R, you still have the `robyn_run` bug? I'm using your `robyn_debug.txt` and the robyn_run function works well with calibration.
regarding the `robyn_recreate` bug, I'll look into it.

**Comment by yanhong-zhao-ef** [comment]
Sorry for the confusion! I really should have opened two separate issues. The original bug reported is for `robyn_recreate` and iyou can run it with the `robyn_debug.txt`. I found this bug while trying to replicate the `robyn_run` bug in my own dataset rather than the simulated dataset. For my own dataset, `robyn_run` bug still exists when I tried running it with the latest code.

Does this make it clear? I can open a separate issue for `robyn_run` bug and we can focus this issue on `robyn_recreate` bug.

**Comment by yanhong-zhao-ef** [comment]
for `robyn_recreate` I did some digging around and found the culprit:

The error is from this line here https://github.com/facebookexperimental/Robyn/blob/main/R/R/outputs.R#L113 where `pareto_results$resultCalibration` is missing a column 'solID'. The current columns are:
```
[1] "rn"               "liftStart"        "liftEnd"          "liftAbs"          "decompStart"     
 [6] "decompEnd"        "decompAbsScaled"  "mape_lift"        "rsq_train"        "nrmse"           
[11] "decomp.rssd"      "mape"             "lambda"           "lambda_hp"        "lambda_max"      
[16] "lambda_min_ratio" "iterPar"          "iterNG"           "df.int"           "trial"         
```

**Comment by yanhong-zhao-ef** [comment]
I am running line by line for the 'robyn_run' bug as well and will report back the result tomorrow when I get to it!

**Comment by gufengzhou** [comment]
Thanks. I can reproduce the error now and will update asap

**Comment by gufengzhou** [comment]
I've just pushed another fix and it runs on my macbook. please update and try

**Comment by yanhong-zhao-ef** [comment]
Thank you @gufengzhou the debug file now runs without a hitch. Let me run on my own data and report back

**Comment by yanhong-zhao-ef** [comment]
There is still an error when running my own data with calibration - I suggest we close this issue and I will open a new one to track that bug.
