### ISSUE TITLE
URGENT - robyn_recreate() with JSON produces different model

### ISSUE THREAD

**Issue by bart-vanvlerken** [facebookexperimental/Robyn#862]
Hi everyone, I have quite an urgent issue I would like your help with. I exported a JSON of a model I selected with a client. The JSON itself is fine, as you can see below (I included the first 5 variables for illustration). 

![image](https://github.com/facebookexperimental/Robyn/assets/118725564/fc3e374e-d002-478a-9fdb-65020e5d3e2e)

When running robyn_recreate(), I produce a completely different model (see below). I would really appreciate your help on this!

![10_270_5](https://github.com/facebookexperimental/Robyn/assets/118725564/e9b04b80-59f8-4b9c-98dd-349f9a27c5a4)

**Comment by bart-vanvlerken** [comment]
I tested robyn_recreate() for another client. Results are again different, but this time not by much. Here is the original model's ROI:

![image](https://github.com/facebookexperimental/Robyn/assets/118725564/7f2dc73b-77af-4101-9a5e-92893aeb438e)

Here is the recreated model's ROI:

![image](https://github.com/facebookexperimental/Robyn/assets/118725564/702d1a96-16ee-43d7-b45f-0dfd2019a60b)

**Comment by gufengzhou** [comment]
sorry for the late reply. There's [another](https://github.com/facebookexperimental/Robyn/issues/800) thread/issue looking into this too, where we've fixed couple of bugs to close this gap. I just tested it and it looks good. Can you pls update to the latest github version and rebuild/retry?

**Comment by bart-vanvlerken** [comment]
I'm using the latest version and the issue still persists unfortunately, shall I send you the JSON + data for debugging?

**Comment by gufengzhou** [comment]
Yes please, gufeng@meta.com

**Comment by bart-vanvlerken** [comment]
UPDATE: I found the cause of the biggest discrepancy (I forgot that I hard-coded the covid variable within InputCollect$dt_mod before running the model). The results are looking better now, but there is still a discrepancy (the output of robyn_recreate still differs from the original). Here are the ROI figures side by side:

ORIGINAL
![image](https://github.com/facebookexperimental/Robyn/assets/118725564/340a7f4c-5abf-4ea2-b2be-906530304e1b)

RECREATED
![image](https://github.com/facebookexperimental/Robyn/assets/118725564/2da97248-a61c-49db-b658-d958bc016abb)

**Comment by bart-vanvlerken** [comment]
Dear @gufengzhou, have you managed to find a cause of the issue? I appreciate the effort!

**Comment by gufengzhou** [comment]
Hey sorry it's been quite busy. I found out that the recreated model has hyperparameters rounded to 4 digits, while the initial one doesn't. But still need to figure out where the rounding is from. will update here once we made progress. @laresbernardo FYI
